local NPC = {
  OAK_START = "#9954",
  OAK_LAB = "#30",
  JACKSON = "Jackson",
  EVEE_PALLET = "#133",
  STARTER_KANTO_BULBASOR ="#11",
  STARTER_KANTO_BULBASOR ="#12",
  STARTER_KANTO_BULBASOR ="#13",
  STARTER_KANTO_PIKACHU ="#11"
}

return NPC